# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: dask_stop
description: Stops a Dask cluster
keywords:
  - dask
  - infrastructure
components:
  - dask_cluster
