# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: cellpose
description: Performs a 3-D segmentation using cellpose distributed on a dask cluster
keywords:
  - dask
  - segmentation
  - cellpose
tools:
  - "cellpose":
      description: "A generalist algorithm for cell and nucleus segmentation."
      homepage: "https://github.com/MouseLand/cellpose"
      documentaton: "https://cellpose.readthedocs.io/en/latest/"
      tool_dev_url: "https://github.com/MouseLand/cellpose"
      license: "['BSD-3-Clause']"
input:
  - meta:
      type: map
      description: |
        Groovy map containing: id, input_image_dataset, output_image_name
  - image:
      type: file
      description: Path to the image container
  - image_subpath:
      type: string
      description: Relative path to the image dataset if needed (for N5 or zarr containers)
  - models_path:
      type: directory
      description: |
        Optional path to the cellpose models cache directory. If this is not specified pass in as empty list.
  - model_name:
      type: string
      description: The name of the cellpose model.
  - output_dir:
      type: directory
      description: Directory location of the output image container
  - labels:
      type: string
      description: Name of the labels container created at the location specified by output_dir
  - labels_subpath:
      type: string
      description: Relative labels dataset subpath
  - working_dir:
      type: directory
      description: |
        Location of the temporary files created during the segmentation. This must have enough space to hold the temporary labels 
        before they are reassigned during the merge process
  - dask_scheduler:
      type: string
      description: Dask scheduler IP
  - dask_config:
      type: file
      description: |
        Optional path to the dask config. If this is not specified pass in as empty list.
  - preprocessing_config:
      type: file
      description: |
        Optional YAML file holding the configuration parameters for various preprocessing operations.
        So far the only preprocessing available is a gaussian filter but there may be more in the future
  - logging_config:
      type: file
      description: Optional log config.
  - cellpose_cpus:
      type: integer
      description: Number of cpus needed to run the main cellpose program
  - cellpose_mem_in_gb:
      type: string
      description: Memory needed for the main cellpose program
output:
  - meta:
      type: map
      description: |
        Groovy map containing: id, input_image_dataset, output_image_name
  - input_image_fullpath:
      type: directory
      description: |
        Full path to the input image container
  - image_subpath:
      type: string
      description: |
        Subpath to the input image dataset
  - output_label_images:
      type: string
      description: |
        One or more image names containing segmentation results. If the output is a zarr or N5 container
        there's only one output_label_image, but if the output type is a tiff and the segmented image is large
        there can be multiple tiff files
  - output_labels_subpath:
        type: string
        description: this is the labels dataset if the output is a zarr or N5 container
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@cgoina"
maintainers:
  - "@cgoina"